export function vcaBuildFullDemoReport() {
  // Minimal, UI-safe demo report. Expand later.
  return {
    headline: "Demo report (safe)",
    topFaults: [],
    rankedFaults: [],
    scores: {},
    practicePlan: [],
    checkpoints: [],
    debug: {
      demo: true,
      note: "Generated by app/lib/report-demo.ts"
    }
  };
}
