name: ping-process-pending

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      PING_URL: "https://virtual-coach-ai-5slg.vercel.app/api/health"

    steps:
      - name: Print target
        run: echo "Pinging \"

      - name: Ping health endpoint (with retries)
        run: |
          set -e
          for i in 1 2 3; do
            curl -fsS --max-time 20 "\" && exit 0
            echo "Attempt \ failed; retrying in 10s…"
            sleep 10
          done
          echo "Health check failed after 3 attempts."
          exit 1
