name: ping-process-pending

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      PING_URL: ${{ secrets.PING_URL }}

    steps:
      - name: Print target
        run: echo "Pinging $PING_URL"

      - name: Ping health endpoint (with retries)
        run: |
          set -e
          for i in 1 2 3; do
            curl -fsS --max-time 20 "$PING_URL" && exit 0
            echo "Attempt $i failed; retrying in 10s…"
            sleep 10
          done
          echo "Health check failed after 3 attempts."
          exit 1
