name: ping-process-pending
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch:        # allow manual runs from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call process-pending
        run: |
          curl -fsS "https://virtualcoachai.net/api/process-pending?token=${{ secrets.CRON_TOKEN }}"
