name: smoke-api
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      SMOKE_URL: https://virtual-coach-ai-5slg.vercel.app/api/health
    steps:
      - name: Check health (GET)
        run: |
          set -e
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$SMOKE_URL")
          echo "HTTP_STATUS=$STATUS"
          if [ "$STATUS" != "200" ]; then
            echo "❌ $SMOKE_URL returned $STATUS"
            exit 1
          fi
      - name: Validate JSON shape (.ok == true)
        run: |
          set -e
          BODY=$(curl -s "$SMOKE_URL")
          echo "$BODY" | jq .
          OK=$(echo "$BODY" | jq -r '.ok // empty')
          if [ "$OK" != "true" ] && [ "$OK" != "True" ]; then
            echo "❌ Response missing ok=true"; exit 1
          fi
